/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.pro1;

import br.udesc.pro1.model.Turma;
import br.udesc.pro1.model.esportes.Futevolei;
import br.udesc.pro1.model.esportes.Volei;
import br.udesc.pro1.model.usuarios.Administrador;
import br.udesc.pro1.model.usuarios.Usuario;
import br.udesc.pro1.utils.Persistencia;
import java.util.ArrayList;

/**
 *
 * @author vitor
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    public static Persistencia persistencia;
    public static Usuario usuarioLogado;
    public static ArrayList<Turma> turmas;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        persistencia = new Persistencia();
        usuarioLogado = new Usuario();
        turmas = gerarTurmas();
        gerarTurmas();
        initComponents();
        TelaLogin telaLogin = new TelaLogin(persistencia, usuarioLogado, turmas);
        telaLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    //Simula persistência de turmas
    private ArrayList<Turma> gerarTurmas() {
        ArrayList<String> escala1 = new ArrayList<String>();
        escala1.add("Seg");
        escala1.add("Qua");
        ArrayList<String> escala2 = new ArrayList<String>();
        escala2.add("Ter");
        escala2.add("Qui");
        Turma turma1 = new Turma("Futevôlei dos Compadres", new Administrador("Mattheus", "4733571234", "mattheus@udesc.br", "1234"), new Futevolei(), "22h", "0h", escala1, null);
        Turma turma2 = new Turma("Vôlei da Marília", new Administrador("Marília", "4733575678", "marilia@udesc.br", "5678"), new Volei(), "22h", "0h", escala2, "Ginásio do IFC");
        ArrayList<Turma> turmas = new ArrayList<>();
        turmas.add(turma1);
        turmas.add(turma2);
        return turmas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
