/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.pro1;

import br.udesc.pro1.model.Turma;
import br.udesc.pro1.model.usuarios.Usuario;
import br.udesc.pro1.utils.Persistencia;

import java.util.ArrayList;

/**
 *
 * @author vitor
 */
public class TelaListaTurmas extends javax.swing.JFrame {
    
    public static Persistencia persistencia;
    public static Usuario usuarioLogado;
    public static ArrayList<Turma> turmas;

    /**
     * Creates new form TelaListaTurmas
     */
    public TelaListaTurmas(Persistencia persistencia, Usuario usuarioLogado, ArrayList<Turma> turmas) {
        TelaListaTurmas.persistencia = persistencia;
        TelaListaTurmas.usuarioLogado = usuarioLogado;
        TelaListaTurmas.turmas = turmas;
        initComponents();
        // {Estou setando estáticamente para a turma 1 como exemplo - temos que descobrir como fazer isso recursivamente para cada turma da lista
        lbTurma.setText(turmas.get(0).getNomeDaTurma());
        lbAdmin.setText(turmas.get(0).getAdministrador().getNome());
        lbEsporteEscolhido.setText(turmas.get(0).getEsporte().getNome());
        lbHorario.setText(turmas.get(0).getHorarioInicio() + " / " + turmas.get(0).getHorarioFim());
        lbJogadores.setText(turmas.get(0).getJogadores().size() + " / " + turmas.get(0).getEsporte().getNUMERO_DE_JOGADORES_MAXIMO());
        // Estou setando estáticamente para a turma 1 como exemplo - temos que descobrir como fazer isso recursivamente para cada turma da lista}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnCadastrarTurma = new javax.swing.JButton();
        lbEncontreSuaTurma = new javax.swing.JLabel();
        scrPnListaTurmas = new javax.swing.JScrollPane();
        pnListaTurmas = new javax.swing.JPanel();
        pnTurma = new javax.swing.JPanel();
        lbEsporteEscolhido = new javax.swing.JLabel();
        lbAdmin = new javax.swing.JLabel();
        lbPor = new javax.swing.JLabel();
        lbEsporte = new javax.swing.JLabel();
        lbJogadores = new javax.swing.JLabel();
        lbTurma = new javax.swing.JLabel();
        lbHorario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(411, 823));
        setResizable(false);
        setSize(new java.awt.Dimension(411, 823));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCadastrarTurma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrarTurma.setText("Cadastrar Turma");
        btnCadastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTurmaActionPerformed(evt);
            }
        });

        lbEncontreSuaTurma.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lbEncontreSuaTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEncontreSuaTurma.setText("Encontre sua turma!");

        scrPnListaTurmas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPnListaTurmas.setPreferredSize(new java.awt.Dimension(399, 596));

        lbEsporteEscolhido.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbEsporteEscolhido.setText("Esporte Escolhido");

        lbAdmin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbAdmin.setText("Admin");

        lbPor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbPor.setText("Por:");

        lbEsporte.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbEsporte.setText("Esporte:");

        lbJogadores.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbJogadores.setText("Membros / Máx.");

        lbTurma.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lbTurma.setText("Titulo");

        lbHorario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbHorario.setText("Inicio / Fim");

        javax.swing.GroupLayout pnTurmaLayout = new javax.swing.GroupLayout(pnTurma);
        pnTurma.setLayout(pnTurmaLayout);
        pnTurmaLayout.setHorizontalGroup(
            pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
            .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTurmaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnTurmaLayout.createSequentialGroup()
                            .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnTurmaLayout.createSequentialGroup()
                                    .addComponent(lbPor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbAdmin))
                                .addComponent(lbHorario))
                            .addGap(25, 25, 25)
                            .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbJogadores)
                                .addGroup(pnTurmaLayout.createSequentialGroup()
                                    .addComponent(lbEsporte)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbEsporteEscolhido)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnTurmaLayout.setVerticalGroup(
            pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTurmaLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(lbTurma)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPor)
                        .addComponent(lbAdmin)
                        .addComponent(lbEsporte)
                        .addComponent(lbEsporteEscolhido))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbHorario)
                        .addComponent(lbJogadores))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnListaTurmasLayout = new javax.swing.GroupLayout(pnListaTurmas);
        pnListaTurmas.setLayout(pnListaTurmasLayout);
        pnListaTurmasLayout.setHorizontalGroup(
            pnListaTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListaTurmasLayout.createSequentialGroup()
                .addComponent(pnTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
        );
        pnListaTurmasLayout.setVerticalGroup(
            pnListaTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListaTurmasLayout.createSequentialGroup()
                .addComponent(pnTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        scrPnListaTurmas.setViewportView(pnListaTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEncontreSuaTurma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrPnListaTurmas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarTurma)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbEncontreSuaTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrPnListaTurmas, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        usuarioLogado = new Usuario();
        this.setVisible(false);
        TelaLogin telaLogin = new TelaLogin(persistencia, usuarioLogado, turmas);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCadastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaTurmas(persistencia, usuarioLogado, turmas).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarTurma;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbEncontreSuaTurma;
    private javax.swing.JLabel lbEsporte;
    private javax.swing.JLabel lbEsporteEscolhido;
    private javax.swing.JLabel lbHorario;
    private javax.swing.JLabel lbJogadores;
    private javax.swing.JLabel lbPor;
    private javax.swing.JLabel lbTurma;
    private javax.swing.JPanel pnListaTurmas;
    private javax.swing.JPanel pnTurma;
    private javax.swing.JScrollPane scrPnListaTurmas;
    // End of variables declaration//GEN-END:variables
}
