/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.pro1;

import br.udesc.pro1.model.Turma;
import br.udesc.pro1.model.esportes.*;
import br.udesc.pro1.model.usuarios.Administrador;
import br.udesc.pro1.model.usuarios.Usuario;
import br.udesc.pro1.utils.Persistencia;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class TelaNovaTurma extends javax.swing.JFrame {
    
    public static Persistencia persistencia;
    public static Usuario usuarioLogado;
    public static ArrayList<Turma> turmas;
    public static Turma novaTurma;

    /**
     * Creates new form TelaNovaTurma
     */
    public TelaNovaTurma(Persistencia persistencia, Usuario usuarioLogado, ArrayList<Turma> turmas) {
        TelaNovaTurma.persistencia = persistencia;
        TelaNovaTurma.usuarioLogado = usuarioLogado;
        TelaNovaTurma.turmas = turmas;
        Administrador administrador = new Administrador(usuarioLogado); //não é possível castar Usuario para Administrador por algum motivo - gambiarra Administrador(Usuario usuario) resolveu :p
        novaTurma = new Turma(administrador); 
        
        initComponents();
        tfAdministrador.setText(usuarioLogado.getNome());
        inicializarEsportes();
        tfNumJogadores.setText((cbEsporte.getItemAt(0).getNUMERO_DE_JOGADORES_MAXIMO().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbAdministrador = new javax.swing.JLabel();
        tfAdministrador = new javax.swing.JTextField();
        lbEsporte = new javax.swing.JLabel();
        cbEsporte = new javax.swing.JComboBox<>();
        lbEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        lbDiasDeJogo = new javax.swing.JLabel();
        tbDiaDom = new javax.swing.JToggleButton();
        tbDiaSeg = new javax.swing.JToggleButton();
        tbDiaTer = new javax.swing.JToggleButton();
        tbDiaQua = new javax.swing.JToggleButton();
        tbDiaQui = new javax.swing.JToggleButton();
        tbDiaSex = new javax.swing.JToggleButton();
        tbDiaSab = new javax.swing.JToggleButton();
        lbHorario = new javax.swing.JLabel();
        lbHorarioInicio = new javax.swing.JLabel();
        lbHorarioFim = new javax.swing.JLabel();
        tfHorarioInicio = new javax.swing.JTextField();
        tfHorarioFim = new javax.swing.JTextField();
        lbNumJogadores = new javax.swing.JLabel();
        tfNumJogadores = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lbNomeDaTurma = new javax.swing.JLabel();
        tfNomeDaTurma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SportMatch - Cadastrar nova turma");
        setMinimumSize(new java.awt.Dimension(411, 823));
        setResizable(false);
        setSize(new java.awt.Dimension(411, 823));

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo.setText("Cadastre sua turma");

        lbAdministrador.setText("Administrador");

        tfAdministrador.setEditable(false);
        tfAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdministradorActionPerformed(evt);
            }
        });

        lbEsporte.setText("Esporte*");

        cbEsporte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsporteActionPerformed(evt);
            }
        });

        lbEndereco.setText("Endereço");

        tfEndereco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbDiasDeJogo.setText("Dias de Jogo*:");

        tbDiaDom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaDom.setText("DOM");
        tbDiaDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaDomActionPerformed(evt);
            }
        });

        tbDiaSeg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaSeg.setText("SEG");
        tbDiaSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaSegActionPerformed(evt);
            }
        });

        tbDiaTer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaTer.setText("TER");
        tbDiaTer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaTerActionPerformed(evt);
            }
        });

        tbDiaQua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaQua.setText("QUA");
        tbDiaQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaQuaActionPerformed(evt);
            }
        });

        tbDiaQui.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaQui.setText("QUI");
        tbDiaQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaQuiActionPerformed(evt);
            }
        });

        tbDiaSex.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaSex.setText("SEX");
        tbDiaSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaSexActionPerformed(evt);
            }
        });

        tbDiaSab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tbDiaSab.setText("SAB");
        tbDiaSab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaSabActionPerformed(evt);
            }
        });

        lbHorario.setText("Horário");

        lbHorarioInicio.setText("Início*");

        lbHorarioFim.setText("Fim*");

        tfHorarioInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tfHorarioFim.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbNumJogadores.setText("Número de jogadores (com reservas)");

        tfNumJogadores.setEditable(false);
        tfNumJogadores.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumJogadoresActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lbNomeDaTurma.setText("Nome da Turma*");

        tfNomeDaTurma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbAdministrador)
                            .addComponent(tfAdministrador)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btnCadastrar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbDiaDom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbDiaSeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbDiaTer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbDiaQua))
                                    .addComponent(lbHorario)
                                    .addComponent(tfEndereco)
                                    .addComponent(lbEsporte)
                                    .addComponent(lbEndereco)
                                    .addComponent(lbDiasDeJogo)
                                    .addComponent(lbNumJogadores)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(tbDiaQui)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbDiaSex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbDiaSab))
                                    .addComponent(cbEsporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNumJogadores))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHorarioInicio)
                                        .addComponent(tfHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHorarioFim)
                                        .addComponent(tfHorarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3)))
                            .addComponent(lbNomeDaTurma)
                            .addComponent(tfNomeDaTurma))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(33, 33, 33)
                .addComponent(lbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeDaTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeDaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEsporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDiasDeJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDiaSeg)
                    .addComponent(tbDiaTer)
                    .addComponent(tbDiaQua)
                    .addComponent(tbDiaDom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDiaSab)
                    .addComponent(tbDiaSex)
                    .addComponent(tbDiaQui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHorarioInicio)
                    .addComponent(lbHorarioFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHorarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumJogadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNumJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCadastrar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsporteActionPerformed
        Esporte esporte = (Esporte) cbEsporte.getSelectedItem();
        tfNumJogadores.setText((esporte.getNUMERO_DE_JOGADORES_MAXIMO().toString()));
        tfNumJogadores.repaint();
    }//GEN-LAST:event_cbEsporteActionPerformed

    private void tbDiaSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaSexActionPerformed
        
    }//GEN-LAST:event_tbDiaSexActionPerformed

    private void tbDiaDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaDomActionPerformed
        
    }//GEN-LAST:event_tbDiaDomActionPerformed

    private void tbDiaSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaSegActionPerformed
        
    }//GEN-LAST:event_tbDiaSegActionPerformed

    private void tbDiaTerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaTerActionPerformed
        
    }//GEN-LAST:event_tbDiaTerActionPerformed

    private void tbDiaQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaQuaActionPerformed
        
    }//GEN-LAST:event_tbDiaQuaActionPerformed

    private void tbDiaQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaQuiActionPerformed
        
    }//GEN-LAST:event_tbDiaQuiActionPerformed

    private void tbDiaSabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaSabActionPerformed
        
    }//GEN-LAST:event_tbDiaSabActionPerformed

    private void tfNumJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumJogadoresActionPerformed
        
    }//GEN-LAST:event_tfNumJogadoresActionPerformed

    private void tfAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdministradorActionPerformed
        
    }//GEN-LAST:event_tfAdministradorActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        ArrayList<String> diasDoJogo = new ArrayList<>();
        if(tbDiaDom.isSelected()) diasDoJogo.add("DOM");
        if(tbDiaSeg.isSelected()) diasDoJogo.add("SEG");
        if(tbDiaTer.isSelected()) diasDoJogo.add("TET");
        if(tbDiaQua.isSelected()) diasDoJogo.add("QUA");
        if(tbDiaQui.isSelected()) diasDoJogo.add("QUI");
        if(tbDiaSex.isSelected()) diasDoJogo.add("SEX");
        if(tbDiaSab.isSelected()) diasDoJogo.add("SAB");
        Esporte esporte = (Esporte) cbEsporte.getSelectedItem();
        try {
            boolean CamposPreenchidos = isCamposPreenchidos();
            if(!isCamposPreenchidos()){
                exibirMensagem("Favor preencher todos os campos obrigatórios(*) e selecione ao menos um dia.");
                return;
            }
            Turma turma = new Turma(tfNomeDaTurma.getText(), novaTurma.getADMINISTRADOR(), esporte, tfHorarioInicio.getText(), tfHorarioFim.getText(), diasDoJogo, tfEndereco.getText());
            turmas.add(turma);
            System.out.println(turma + " cadastrada.");
            exibirMensagem("Turma " + turma.getNomeDaTurma() + " cadastrada com sucesso!");
            voltar();
        } catch (Exception e) {
            exibirMensagem("Erro: "+e);
            voltar();
        } 
            
        
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovaTurma(persistencia, usuarioLogado, turmas).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Esporte> cbEsporte;
    private javax.swing.JLabel lbAdministrador;
    private javax.swing.JLabel lbDiasDeJogo;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEsporte;
    private javax.swing.JLabel lbHorario;
    private javax.swing.JLabel lbHorarioFim;
    private javax.swing.JLabel lbHorarioInicio;
    private javax.swing.JLabel lbNomeDaTurma;
    private javax.swing.JLabel lbNumJogadores;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JToggleButton tbDiaDom;
    private javax.swing.JToggleButton tbDiaQua;
    private javax.swing.JToggleButton tbDiaQui;
    private javax.swing.JToggleButton tbDiaSab;
    private javax.swing.JToggleButton tbDiaSeg;
    private javax.swing.JToggleButton tbDiaSex;
    private javax.swing.JToggleButton tbDiaTer;
    private javax.swing.JTextField tfAdministrador;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfHorarioFim;
    private javax.swing.JTextField tfHorarioInicio;
    private javax.swing.JTextField tfNomeDaTurma;
    private javax.swing.JTextField tfNumJogadores;
    // End of variables declaration//GEN-END:variables

    private void inicializarEsportes() {
        cbEsporte.removeAllItems();
        Futebol futebol = new Futebol();
        Volei volei = new Volei();
        Futsal futsal = new Futsal();
        Futevolei futevolei = new Futevolei();
        cbEsporte.addItem(futebol);
        cbEsporte.addItem(volei);
        cbEsporte.addItem(futsal);
        cbEsporte.addItem(futevolei);
    }

    public boolean isCamposPreenchidos() {
        boolean diaSelecionado = isDiaSelecionado();
        return (
                ((!tfNomeDaTurma.getText().isBlank() || !tfNomeDaTurma.getText().isEmpty() || !tfNomeDaTurma.getText().equals("")) &&
                (!tfHorarioInicio.getText().isBlank() || !tfHorarioInicio.getText().isEmpty() || !tfHorarioInicio.getText().equals("")) &&
                (!tfHorarioFim.getText().isBlank() || !tfHorarioFim.getText().isEmpty() || !tfHorarioFim.getText().equals(""))) &&
                diaSelecionado
        );
    }
    
    public boolean isDiaSelecionado(){
        return (tbDiaDom.isSelected() ||
                tbDiaSeg.isSelected() ||
                tbDiaTer.isSelected() ||
                tbDiaQua.isSelected() ||
                tbDiaQui.isSelected() ||
                tbDiaSex.isSelected() ||
                tbDiaSab.isSelected()
                );
    }
    
    public void exibirMensagem(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void voltar(){
        this.setVisible(false);
        TelaListaTurmas telaListaTurmas = new TelaListaTurmas(persistencia, usuarioLogado, turmas);
        telaListaTurmas.setVisible(true);
        this.dispose();
    }
}
